// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX907MRgtvjTlv9oSm-aRXT9POzb0CHIk',
    appId: '1:416426862446:web:dd256fe5a1f4b83838c37f',
    messagingSenderId: '416426862446',
    projectId: 'adv-exam-2nd',
    authDomain: 'adv-exam-2nd.firebaseapp.com',
    storageBucket: 'adv-exam-2nd.appspot.com',
    measurementId: 'G-PYS2TZC4L3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR-K8X-v20SYfHtUYU9tlT1036K1O1h_M',
    appId: '1:416426862446:android:59ff6b6b1e838bcc38c37f',
    messagingSenderId: '416426862446',
    projectId: 'adv-exam-2nd',
    storageBucket: 'adv-exam-2nd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT_-Lwk_unZt7rM6FFAr5p5y-UDZdUgmI',
    appId: '1:416426862446:ios:e9048857b0f8fa0c38c37f',
    messagingSenderId: '416426862446',
    projectId: 'adv-exam-2nd',
    storageBucket: 'adv-exam-2nd.appspot.com',
    iosBundleId: 'com.example.advExam2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAT_-Lwk_unZt7rM6FFAr5p5y-UDZdUgmI',
    appId: '1:416426862446:ios:e9048857b0f8fa0c38c37f',
    messagingSenderId: '416426862446',
    projectId: 'adv-exam-2nd',
    storageBucket: 'adv-exam-2nd.appspot.com',
    iosBundleId: 'com.example.advExam2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAX907MRgtvjTlv9oSm-aRXT9POzb0CHIk',
    appId: '1:416426862446:web:f247376cd8ca31e338c37f',
    messagingSenderId: '416426862446',
    projectId: 'adv-exam-2nd',
    authDomain: 'adv-exam-2nd.firebaseapp.com',
    storageBucket: 'adv-exam-2nd.appspot.com',
    measurementId: 'G-37KB8MHGZT',
  );
}
